const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const flightSchema=new Schema({
    flightNumber:{
        type:String,
        required:true,
    },
    date:{
        type:Date,
        required:true,
    },
    capacity:{
        type:Number,
        required:true,
    },
    airplane:{
        type:String,
        required:true,
    },
    airport:{
        type:String,
        required:true,
    },
    arrivalTime:{
        type:Date,
        required:true,
    },
    startingTime:{
        type:Date,
        required:true,
    },
    flyFrom:{
        type:String,
        required:true,
    },
    flyTo:{
        type:String,
        required:true,
    },
    seats:[{
        openSeats:{
            type:Number,
            required:true,
        },
    }]
},
{timestamps:true},
)
module.exports=mongoose.model('Flight',flightSchema);